"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-35@kyke(hiyo*6*@jjxjhs2*-#f@c@bu1=ws2k-2fsh9k3rw1t'
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
DEBUG = config('DEBUG', default = False, cast = bool)

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default = '', cast = Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    "telegram_bot",
]

MIDDLEWARE = [
    # безопасность (HTTPS, XSS защита)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # работа с сессия
    'django.contrib.sessions.middleware.SessionMiddleware',
    # общие вещи (редиректы, просмотры)
    'django.middleware.common.CommonMiddleware',
    # защита от CSRF атак
    'django.middleware.csrf.CsrfViewMiddleware',
    # аутентификация пользователя
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # система сообщений
    'django.contrib.messages.middleware.MessageMiddleware',
    # защита от clickjacking атак
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Кастомные middleware
    'shop.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
                'shop.context_processors.shop_context',
                'shop.context_processors.support_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT', default='5432'),
        'CONN_MAX_AGE': 600,  # Кэширование соединений
        'OPTIONS': {
            'sslmode': 'require',  # Обязательно для Railway
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Куда перенаправлять при успешном входе
LOGIN_REDIRECT_URL = 'shop:home'

# Куда перенаправлять после выхода
LOGOUT_REDIRECT_URL = 'shop:home'

# Страница входа, если пользователь не авторизован
LOGIN_URL = 'shop:login'

# Время жизни сессии(в секундах)
SESSION_COOKIE_AGE = 1209600 # 2 недели

# Использование HTTPS для кук сессии (В продакшене True)
SESSION_COOKIE_SECURE = False

# Название кук сессии
SESSION_COOKIE_NAME = 'sessionid'

#Довкренные источники
CSRF_TRUSTED_ORIGINS = [
    'https://web-production-a61b3.up.railway.app',
    'https://*.railway.app',
]

# TELEGRAM_BOT
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_ADMIN_IDS = config('TELEGRAM_ADMIN_IDS', default='', cast=Csv())