# Generated by Django 6.0.2 on 2026-02-26 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='На этот email придёт ответ', max_length=254, verbose_name='Email для связи')),
                ('subject', models.CharField(help_text='Кратко опишите суть вопроса', max_length=200, verbose_name='Тема обращения')),
                ('category', models.CharField(choices=[('Вопрос', 'question'), ('Жалоба', 'complant'), ('suggestion', 'Предложение'), ('technical', 'Техническая проблема'), ('Другое', 'other')], default='question', max_length=20, verbose_name='Категория')),
                ('message', models.TextField(help_text='Подробно опишите вашу проблему или вопрос', max_length=5000, verbose_name='Текст обращения')),
                ('status', models.CharField(choices=[('Новые', 'new'), ('В процессе', 'in_progress'), ('resolved', 'решено'), ('закрыто', 'closed')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'низкий'), ('medium', 'средний'), ('high', 'высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('response', models.TextField(blank=True, help_text='Ответ будет виден только после публикации', null=True, verbose_name='Ответ администрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Обращение решено')),
                ('is_public', models.BooleanField(default=False, help_text='Если отмечено, ответ будет виден пользователю', verbose_name='Опубликовать ответ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение в поддержку',
                'verbose_name_plural': 'Обращение в поддержку',
                'db_table': 'support_tickets',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Максимальный размер 5МБ', upload_to='support_attachments/', verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shop.supportticket', verbose_name='Образение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложение',
                'db_table': 'support_ticket_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='tickets_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='ticket_category_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['email'], name='ticket_email_idx'),
        ),
    ]
