# Generated by Django 5.2.12 on 2026-03-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_supportticket_supportticketattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('Вопрос', 'question'), ('Жалоба', 'complant'), ('Предложение', 'suggestion'), ('technical', 'Техническая проблема'), ('Другое', 'other')], default='question', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('низкий', 'low'), ('средний', 'medium'), ('high', 'высокий'), ('Срочный', 'urgent')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Новые', 'new'), ('В процессе', 'in_progress'), ('решено', 'resolved'), ('закрыто', 'closed')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Для связи и уведомлений', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Формат: +7 (XXX) XXX-XX-XX', max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(help_text='Город, улица, дом, квартира', verbose_name='Адрес доставки')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('status', models.CharField(choices=[('new', '🆕 Новый'), ('processing', '🔄 В обработке'), ('paid', '💳 Оплачен'), ('shipped', '📦 Отправлен'), ('delivered', '✅ Доставлен'), ('cancelled', '❌ Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('card', '💳 Банковская карта'), ('cash', '💵 Наличные'), ('online', '🌐 Онлайн оплата')], default='card', max_length=20, verbose_name='Способ оплаты')),
                ('delivery_method', models.CharField(choices=[('pickup', '🏪 Самовывоз'), ('courier', '🚚 Курьер'), ('post', '📮 Почта'), ('cdek', '📦 CDEK')], default='courier', max_length=20, verbose_name='Способ доставки')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая сумма')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Скидка')),
                ('final_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая сумма')),
                ('comment', models.TextField(blank=True, help_text='Пожелания к доставке', verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трекинг номер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена на момент заказа', max_digits=10, verbose_name='Цена за единицу')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'db_table': 'cart_items',
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='order_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
