# Generated by Django 5.2.12 on 2026-03-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_supportticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('Вопрос', 'question'), ('complant', 'Жалоба'), ('Предложение', 'suggestion'), ('technical', 'Техническая проблема'), ('other', 'Другое')], default='question', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'низкий'), ('medium', 'средний'), ('high', 'высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('Новые', 'new'), ('В процессе', 'in_progress'), ('решено', 'resolved'), ('closed', 'закрыто')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
